sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t paulpatena/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true paulpatena/react-test npm test

after_success:
  - docker build -t paulpatena/multi-client ./client
  - docker build -t paulpatena/multi-nginx ./nginx
  - docker build -t paulpatena/multi-server ./server
  - docker build -t paulpatena/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push paulpatena/multi-client
  - docker push paulpatena/multi-nginx
  - docker push paulpatena/multi-server
  - docker push paulpatena/multi-worker

deploy"
  provider: elasticbeanstalk
  region: 'ap-southeast-2'
  app: 'multi-docker-syd'
  env: 'Multidockersyd-env'
  bucketname: 'elasticbeanstalk-ap-southeast-2-772544791412'
  bucket_path: 'docker-multi'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
